BookList/BookList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('BookListAPI.urls'))
]

Books/Books/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

demoproj/demoproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("demoapp.urls"))
]

pollSite/pollSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

statesAir/airport/urls.py
from . import views
from django.urls import path

app_name = 'airport'

urlpatterns = [
    path('', views.home, name = "home"),
    path('create_emp/', views.create_emp, name = "create_emp"),
    path('create_plane/', views.create_plane, name = "create_plane"),
    path('create_flight/', views.create_flight, name = "create_flight"),
    path('list_deps/', views.list_deps, name = "list_deps"),
    path('list_emps/', views.list_emps, name = "list_emps"),
    path('list_planes/', views.list_planes, name = "list_planes"),
    path('list_flights/', views.list_flights, name = "list_flights"),
    path('list_crews/', views.list_crews, name = "list_crews"),
    path('edit_emp/', views.edit_emp, name = "edit_emp"),
    path('edit_plane/', views.edit_plane, name = "edit_plane"),
    path('edit_crew/', views.edit_crew, name = "edit_crew"),
]

statesAir/airport/models.py
from django.db import models

# Create your models here.
class Plane(models.Model):
    class PlaneType(models.TextChoices):
        CARGO = 'Cargo',
        PASSENGER = 'Passenger',
        PRIVATE = 'Private'
    class PlaneStatus(models.TextChoices):
        ACTIVE = 'Active',
        INACTIVE = 'Inactive',
        DECOMMISSIONED = 'Decommissioned',
        REPAIR = 'Repair',
    plane_id = models.IntegerField(primary_key=True)
    plane_type = models.TextField(choices = PlaneType.choices, default='Passenger')
    capacity = models.IntegerField()
    plane_status = models.TextField(choices = PlaneStatus.choices, default='Active')
    plane_airline = models.CharField(max_length=50)
    commission_date = models.DateField()

    def __str__(self):
        return f"{self.plane_id} - {self.plane_airline} - {self.capacity}."
    
    
class Department(models.Model):
    class DepartmentName(models.TextChoices):
        PILOT = 'Pilot', 'Pilot'
        FLIGHT_ATTENDANT = 'Flight Attendant', 'Flight Attendant'
        MECHANIC = 'Mechanic', 'Mechanic'
        GROUND_CREW = 'Ground Crew', 'Ground Crew'
        CONCESSIONS = 'Concessions', 'Concessions'
        JANITOR = 'Janitor', 'Janitor'
        SECURITY = 'Security', 'Security'
        ADMIN = 'Admin', 'Admin'
    dept_id = models.IntegerField(primary_key=True)
    dept_name = models.TextField(choices=DepartmentName.choices, default='Admin', unique=True)
    dept_location = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.dept_name}"
    
class Employee(models.Model):
    emp_id = models.IntegerField(primary_key=True)
    emp_fname = models.CharField(max_length=20)
    emp_lname = models.CharField(max_length=20)
    emp_date = models.DateField()
    emp_role = models.ForeignKey(Department, on_delete=models.CASCADE)
    emp_sal = models.IntegerField()

    def __str__(self):
        return f"Employee {self.emp_id} - {self.emp_fname} {self.emp_lname}: {self.emp_role}."
    
class Crew(models.Model):
    crew_id = models.IntegerField(primary_key=True)
    crew_staff = models.ManyToManyField(Employee, limit_choices_to={'emp_role__dept_name': 'Pilot', 'emp_role__dept_name': 'FlightAttendant'}) 

    def __str__(self):
        return f"Crew {self.crew_id} - {self.crew_staff.count()} members."

class Flight(models.Model):
    class FlightStatus(models.TextChoices):
        ONTIME = 'On Time', 'On Time'
        DELAYED = 'Delayed', 'Delayed'
        CANCELLED = 'Cancelled', 'Cancelled'
    flight_id = models.IntegerField(primary_key=True)
    flight_status = models.TextField(choices=FlightStatus.choices, default='On Time')
    flight_origin = models.CharField(max_length=50)
    flight_destination = models.CharField(max_length=50)
    flight_departure = models.DateTimeField()
    flight_arrival = models.DateTimeField()
    flight_plane = models.ForeignKey(Plane, on_delete=models.CASCADE)
    flight_crew = models.ForeignKey(Crew, on_delete=models.CASCADE, default = 1)

    def __str__(self):
        return f"Flight {self.flight_id} is a {self.flight_plane} from {self.flight_origin} to {self.flight_destination}."

statesAir/airport/forms.py
from django import forms

from .models import Plane, Flight, Department, Employee, Crew

class CreateDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = "__all__"

class CreateEmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"
        widgets = {
            'emp_date': forms.DateInput(attrs={'type': 'date'})
        }

class EditEmployeeForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all())

class CreatePlaneForm(forms.ModelForm):
    class Meta:
        model = Plane
        fields = "__all__"
        widgets = {
            'commission_date': forms.DateInput(attrs={'type': 'date'})
        }

class EditPlaneForm(forms.Form):
    plane = forms.ModelChoiceField(queryset=Plane.objects.all())

class CreateFlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = "__all__"
        widgets = {
            'flight_departure': forms.DateInput(attrs={'type': 'date'}),
            'flight_arrival': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super(CreateFlightForm, self).__init__(*args, **kwargs)
        self.fields['flight_plane'].queryset = Plane.objects.filter(plane_status='Active')
        
class CreateCrewForm(forms.ModelForm):
    class Meta:
        model = Crew
        fields = "__all__"

class EditCrewForm(forms.Form):
    crew = forms.ModelChoiceField(queryset=Crew.objects.all())

statesAir/airport/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from .forms import *
from .models import Employee, Department, Plane, Flight, Crew

def home(request):
    return render(request, 'airport/home.html')

def create_dep(request):
    form = CreateDepartmentForm()
    if request.method == "POST":
        form = CreateDepartmentForm(request.POST)
        if form.is_valid():
            form.save()
    context = {"form" : form}
    return render(request, 'airport/create_dep.html', context)

def create_emp(request):
    form = CreateEmployeeForm()
    if request.method == "POST":
        form = CreateEmployeeForm(request.POST)
        if form.is_valid():
            form.save()
    context = {"form" : form}
    return render(request, 'airport/create_emp.html', context)

def create_plane(request):
    form = CreatePlaneForm()
    if request.method == "POST":
        form = CreatePlaneForm(request.POST)
        if form.is_valid():
            form.save()
    context = {"form" : form}
    return render(request, 'airport/create_plane.html', context)

def create_flight(request):
    form = CreateFlightForm()
    if request.method == "POST":
        form = CreateFlightForm(request.POST)
        if form.is_valid():
            form.save()
    context = {"form" : form}
    return render(request, 'airport/create_flight.html', context)

def list_deps(request):
    deps = Department.objects.all()
    content = {"deps" : deps}
    return render(request, 'airport/list_deps.html', content)

def list_emps(request):
    emps = Employee.objects.all()
    content = {"emps" : emps}
    return render(request, 'airport/list_emps.html', content)

def list_planes(request):
    planes = Plane.objects.all()
    content = {"planes" : planes}
    return render(request, 'airport/list_planes.html', content)

def list_flights(request):
    flights = Flight.objects.all()
    content = {"flights" : flights}
    return render(request, 'airport/list_flights.html', content)

def list_crews(request):
    crews = Crew.objects.all().prefetch_related('crew_staff')
    content = {"crews" : crews}
    return render(request, 'airport/list_crews.html', content)

def edit_emp(request):
    emp = None
    select = EditEmployeeForm()
    edit = CreateEmployeeForm()

    if request.method == "GET":
        if 'employee' in request.GET:
            emp = Employee.objects.get(pk = int(request.GET.get('employee')))
            select = EditEmployeeForm(initial={'employee': emp})
            edit = CreateEmployeeForm(instance=emp)
        
    elif request.method == "POST": 
        emp = Employee.objects.get(pk=request.GET.get('employee'))
        edit = CreateEmployeeForm(request.POST, instance=emp)
        if edit.is_valid():
            edit.save()
    
    return render(request, 'airport/edit_emp.html', {"select": select, "form" : edit})

def edit_plane(request):
    plane = None
    select = EditPlaneForm()
    edit = CreatePlaneForm()

    if request.method == "GET":
        if 'plane' in request.GET:
            plane = Plane.objects.get(pk = int(request.GET.get('plane')))
            select = EditPlaneForm(initial={'plane': plane})
            edit = CreatePlaneForm(instance=plane)
        
    elif request.method == "POST": 
        plane = Plane.objects.get(pk=request.GET.get('plane'))
        edit = CreatePlaneForm(request.POST, instance=plane)
        if edit.is_valid():
            edit.save()
    
    return render(request, 'airport/edit_plane.html', {"select": select, "form" : edit})

def edit_crew(request):
    crew = None
    select = EditCrewForm()
    selectEmp = EditEmployeeForm()
    selectEmp.fields['employee'].queryset = Employee.objects.filter(emp_role__dept_name='Pilot') | Employee.objects.filter(emp_role__dept_name='FlightAttendant')
    selectEmp2 = EditEmployeeForm()

    if request.method == "GET":
        if 'crew' in request.GET:
            crew = Crew.objects.get(pk = int(request.GET.get('crew')))
            select = EditCrewForm(initial={'crew': crew})
            selectEmp.fields['employee'].queryset = Employee.objects.filter(emp_role__dept_name='Pilot') | Employee.objects.filter(emp_role__dept_name='FlightAttendant')
            selectEmp.fields['employee'].queryset = selectEmp.fields['employee'].queryset.exclude(emp_id__in=crew.crew_staff.all())
            selectEmp2.fields['employee'].queryset = crew.crew_staff.all()
        
    elif request.method == "POST":
        if 'type' in request.POST:
            crew = Crew.objects.get(pk=request.GET.get('crew'))
            if request.POST.get('type') == "add":
                print("Added: "+ request.POST.get('employee'))
                crew.crew_staff.add(Employee.objects.get(pk=request.POST.get('employee')))
            else:
                print("Removed: "+ request.POST.get('employee'))
                crew.crew_staff.remove(Employee.objects.get(pk=request.POST.get('employee')))
            crew.save()

    return render(request, 'airport/edit_crew.html', {"select": select, "selectEmp": selectEmp, "selectEmp2": selectEmp2})

statesAir/airport/templates/airport/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>States Air</title>
    <!-- Add your CSS stylesheets and JavaScript files here -->
    <link rel="stylesheet" href= "{% static 'airport/style.css' %}">
    
</head>

<body>
    <!-- Add your header content here -->
    {% include "airport/header.html" %}

    <!-- Add your main content here -->
    <main>
        {% block content %}
        
        
        
        {% endblock %}
    </main>

    <!-- Add your footer content here -->
    <footer>
        &copy; 2024 States Air. All rights reserved.
    </footer>
</body>
</html>

statesAir/airport/templates/airport/create_dep.html
{% extends 'airport/base.html' %}

{% block content %}

<form method = POST>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>

    <button type = "submit" value = "Create">Create</button>
</form>

{% endblock %}

statesAir/airport/templates/airport/create_emp.html
{% extends "airport/base.html" %}

{% block content %}

<h2>Create Employee</h2>

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    
    <button type="submit">Create</button>
</form>

{% endblock %}

statesAir/airport/templates/airport/create_flight.html
{% extends "airport/base.html" %}

{% block content %}

    <h2> Create Plane </h2>

    <form method = "POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        
        <button type= "Submit">Create</button>
    </form>

{% endblock %}

statesAir/airport/templates/airport/create_plane.html
{% extends "airport/base.html" %}

{% block content %}

    <h2> Create Plane </h2>

    <form method = "POST" id = "actualEmp">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        
        <button type= "Submit">Create</button>
    </form>
    
{% endblock %}

statesAir/airport/templates/airport/edit_crew.html
{% extends 'airport/base.html' %}

{% block content %}

    <h2>Edit Crew</h2>

    <h3>Select Crew</h3>

    <form method="GET">
        {% csrf_token %}
        <table>
            {{ select.as_table }}
        </table>
        <button type="submit">Select</button>
        <button type="delete">Delete</button>
    </form>


    <h3>Add Employee to Crew</h3>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ selectEmp.as_table }}
        </table>
        <input type="hidden" name="type" value="add" />
        <button type="submit">Add</button>
    </form>

    <h3>Remove Employee from Crew</h3>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ selectEmp2.as_table }}
        </table>
        <input type="hidden" name="type" value="remove" />
    <button type="submit">Remove</button>


{% endblock %}

statesAir/airport/templates/airport/edit_emp.html
{% extends 'airport/base.html' %}

{% block content %}

    <h2>Edit Employee</h2>

    <form method="GET">
        {% csrf_token %}
        <table>
            {{ select.as_table }}
        </table>

    <button type="submit">Select</button>
    </form>


    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Save</button>
    </form>

{% endblock %}  

statesAir/airport/templates/airport/edit_plane.html
{% extends 'airport/base.html' %}

{% block content %}

    <h2>Edit Plane</h2>

    <form method="GET">
        {% csrf_token %}
        <table>
            {{ select.as_table }}
        </table>
        <button type="submit">Select</button>
    </form>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    <button type="submit">Save</button>

{% endblock %}

statesAir/airport/templates/airport/header.html
<header class="header">
    <nav class="navbar">
        <ul>
            <a href = "{% url 'airport:home' %}">Home</a>
            <a href = "{% url 'airport:list_deps' %}">List Departments</a>
            <a href = "{% url 'airport:list_emps' %}">List Employees</a>
            <a href = "{% url 'airport:list_planes' %}">List Planes</a>
            <a href = "{% url 'airport:list_flights' %}">List Flights</a>
            <a href = "{% url 'airport:list_crews' %}">List Crews</a>
            <a href= '{% url "airport:create_emp"  %}'>Create Employee</a>
            <a href= '{% url "airport:create_plane"  %}'>Create Plane</a>
            <a href= '{% url "airport:create_flight"  %}'>Create Flight</a>
            <a href= '{% url "airport:edit_emp" %}'>Edit Employee</a>
            <a href= '{% url "airport:edit_plane" %}'>Edit Plane</a>
            <a href = '{% url "airport:edit_crew" %}'>Edit Crew</a>
        </ul>
    </nav>
</header>

statesAir/airport/templates/airport/home.html
{% extends "airport/base.html" %}

{% block content %}

<h1> This is the Airport Application </h1>

<h2> Something</h2>

{% endblock %}

statesAir/airport/templates/airport/list_crews.html
{% extends 'airport/base.html' %}

{% block content %}

    <h2> This is a list of Crews </h2>

    {% for c in crews %}
        <h3>Crew {{c.crew_id}}</h3>

        <table>
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Employee Position</th>
                <th>Employee Status</th>
            </tr>

            {% for e in c.crew_staff.all %}
                <tr>
                    <td>{{ e.emp_id }}</td>
                    <td>{{ e.emp_fname }}</td>
                    <td>{{ e.emp_lname }}</td>
                    <td>{{ e.emp_role.dept_name }}</td>
                </tr>
            {% endfor %}

        </table>

    {% endfor %}

{% endblock %}

statesAir/airport/templates/airport/list_deps.html
{% extends "airport/base.html" %}


{% block content %}

<h2>This is a list of Departments</h2>

<th>
    <table>
        <tr>
            <th>Department Name</th>
            <th>Department Number</th>
            <th>Location</th>
        </tr>
        
        {% for dep in deps %}
        <tr>
            <td>{{dep.dept_name}}</td>
            <td>{{dep.dept_id}}</td>
            <td>{{dep.dept_location}}</td>
        </tr>
        {% endfor %}
    </table>
</th>


{% endblock %}

statesAir/airport/templates/airport/list_flights.html
{% extends "airport/base.html" %}


{% block content %}

<h2>This is a list of Flights.</h2>

<table>
    <tr>
        <th>Flight ID</th>
        <th>Status</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Departure</th>
        <th>Arrival</th>
        <th>Plane</th>
    </tr>

    {% for flight in flights %}
    <tr>
        <td>{{ flight.flight_id }}</td>
        <td>{{ flight.flight_status }}</td>
        <td>{{ flight.flight_origin }}</td>
        <td>{{ flight.flight_destination }}</td>
        <td>{{ flight.flight_departure }}</td>
        <td>{{ flight.flight_arrival }}</td>
        <td>{{ flight.flight_plane }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

statesAir/airport/templates/airport/list_planes.html
{% extends "airport/base.html" %}


{% block content %}

<h2>This is a list of Planes.</h2>

<table>

    <tr>

        <th>Plane ID</th>
        <th>Plane Type</th>
        <th>Plane Capacity</th>
        <th>Plane Status</th>
        <th>Airline </th>
        <th>Commission Date</th>

    </tr>
    
    {% for plane in planes %}

    <tr>
        <td>{{ plane.plane_id }}</td>
        <td>{{ plane.plane_type}}</td>
        <td>{{ plane.capacity }}</td>
        <td>{{ plane.plane_status }}</td>
        <td>{{ plane.plane_airline }}</td>
        <td>{{ plane.commission_date }}</td>
    </tr>

    {% endfor %}

</table>
    
{% endblock %}